version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: University
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    links:
      - mysql:db
    ports:
      - 8080:80

  system:    
    build: 
      context: .
      dockerfile: docker/system/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    command: go run main.go

volumes:
  my-datavolume: