version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: University
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      testing_net:
          ipv4_address: 172.28.1.1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    links:
      - mysql:db
    ports:
      - 8080:80
    networks:
      testing_net:
          ipv4_address: 172.28.1.2

  system:    
    build: 
      context: .
      dockerfile: docker/system/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    command: go run main.go
    networks:
      testing_net:
          ipv4_address: 172.28.1.3

volumes:
  my-datavolume:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16